spring.application.name=iyunga-tech-sec-school

#DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/AMOS BAHAME
spring.datasource.username=postgres
spring.datasource.password=amos123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


